source 'https://rubygems.org'

gem 'rest-client'
gem 'activerecord', '7.0.3.1'
gem 'seapig-client-ruby'

gem 'pg'
gem 'daemons'
gem 'awesome_print'
gem 'rake'
gem 'json'
gem 'typhoeus'
gem 'mime-types'
gem 'graphmatcher'
gem 'xmlrpc'
